//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace GuildQuest.Data.EF
{
    public partial class State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public State()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int StateId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Country { get; set; }
        public string Type { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Status { get; set; }
        public string Occupied { get; set; }
        public string Notes { get; set; }
        public string FipsState { get; set; }
        public string AssocPress { get; set; }
        public string StandardFederalRegion { get; set; }
        public string CensusRegion { get; set; }
        public string CensusRegionName { get; set; }
        public string CensusDivision { get; set; }
        public string CensusDivisionName { get; set; }
        public string CircuitCourt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
