//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace GuildQuest.UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Sale
    {
        public int SaleId { get; set; }
        public int VehicleId { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }

        [DisplayName("Street 1")]
        public string Street1 { get; set; }

        [DisplayName("Street 2")]
        public string Street2 { get; set; }

        public string City { get; set; }

        [DisplayName("State")]
        public int StateId { get; set; }

        [DisplayName("Zip Code")]
        public string ZipCode { get; set; }

        [DisplayName("Purchase Price")]
        public decimal PurchasePrice { get; set; }

        [DisplayName("Purchase Type")]
        public int PurchaseTypeId { get; set; }

        [DisplayName("Purchase Type")]
        public virtual PurchaseType PurchaseType { get; set; }

        [DisplayName("State")]
        public virtual State State { get; set; }

        public virtual Vehicle Vehicle { get; set; }

        public SelectList StateList { get; set; }
        public SelectList PurchaseTypeList { get; set; }
    }
}
